// resources/js/partials/footer.tsx
import { Link } from '@inertiajs/react';
import { ArrowUpRight, Facebook, Instagram, MapPin, Music2 } from 'lucide-react';

// lucide-react only ships the old bird logo under "Twitter" — the current X wordmark isn't in
// its icon set, so it's drawn here to match the other icons' sizing/stroke conventions.
function XLogo({ className }: { className?: string }) {
    return (
        <svg viewBox="0 0 24 24" fill="currentColor" className={className}>
            <path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z" />
        </svg>
    );
}

const SOCIAL_LINKS = [
    { icon: Facebook, label: 'Facebook', href: 'https://www.facebook.com/BrignacMortgage' },
    { icon: MapPin, label: 'Find us on Google Maps', href: 'https://maps.app.goo.gl/kSBdEXrM5XXNnSBE7' },
    { icon: XLogo, label: 'X', href: 'https://x.com/shaunbrignac' },
    { icon: Music2, label: 'TikTok', href: 'https://www.tiktok.com/@shaunbrignac' },
    { icon: Instagram, label: 'Instagram', href: 'https://www.instagram.com/shaunbrignac' },
];

const LEGAL_LINKS = [
    { label: 'Disclaimers', href: '/disclaimers' },
    { label: 'Privacy Policy', href: '/privacy-policy' },
    { label: 'Terms and Conditions', href: '/terms-and-conditions' },
];

export function Footer({ dark = false }: { dark?: boolean }) {
    return (
        <footer className="mx-auto mt-10 flex max-w-6xl flex-col items-center gap-8 px-4 sm:flex-row sm:items-end sm:justify-between sm:gap-0 sm:px-6 lg:px-8">
            <div className="order-1 flex w-full flex-col items-center gap-5 text-center sm:order-0 sm:mb-5 sm:w-[20%] sm:items-start sm:text-left">
                <h2 className="text-lg leading-[1.1] text-foreground">
                    Brignac <span className="text-primary">Mortgage</span>
                </h2>
                <div className="flex items-center gap-x-2">
                    {SOCIAL_LINKS.map((social) => {
                        const Icon = social.icon;

                        return (
                            <a
                                key={social.label}
                                href={social.href}
                                target="_blank"
                                rel="noopener noreferrer"
                                aria-label={social.label}
                                className="grid size-9 place-items-center rounded-full text-foreground/60 transition-colors hover:text-primary"
                            >
                                <Icon className="size-4.5" />
                            </a>
                        );
                    })}
                </div>

                <p className="text-[11px] leading-relaxed text-foreground/40">
                    Copyright © 2026 Brignac Mortgage and Consulting Services LLC - All Rights reserved. NMLS #2401214
                    <br />
                    Equal Housing Opportunity Lender
                </p>
            </div>

            <div
                data-header-theme={dark ? 'dark' : undefined}
                className={`order-3 mx-auto flex w-full max-w-2xl items-center justify-center sm:order-0 sm:w-[60%] ${dark ? 'bg-background' : 'bg-white'}`}
            >
                <img
                    src={dark ? '/img/dark_footer.png' : '/img/footer.png'}
                    alt="lion Brignac Mortgage"
                    className="h-full w-full"
                />
            </div>

            <div className="order-2 flex w-full flex-col items-center gap-5 text-center sm:order-0 sm:mb-5 sm:w-[20%] sm:items-end sm:text-right">
                <Link
                    href="/apply"
                    className="group inline-flex items-center gap-2 rounded-full bg-primary py-2 pr-2 pl-4 text-sm font-medium text-primary-foreground transition-colors hover:bg-primary/90"
                >
                    About Us
                    <span className="grid size-6 shrink-0 place-items-center rounded-full bg-primary-foreground/15 transition-transform duration-200 ease-out group-hover:-translate-y-0.5 group-hover:translate-x-0.5">
                        <ArrowUpRight className="size-3.5" />
                    </span>
                </Link>

                <div className="flex flex-col gap-2">
                    {LEGAL_LINKS.map((link) => (
                        <Link
                            key={link.href}
                            href={link.href}
                            className="text-sm text-foreground/60 transition-colors hover:text-foreground"
                        >
                            {link.label}
                        </Link>
                    ))}
                </div>
            </div>
        </footer>
    );
}

// resources/js/Components/Footer.vue
<script setup>
import { Link } from '@inertiajs/vue3';
import useCurrentYear from '@/composables/currentYear';

const { currentYear } = useCurrentYear();
</script>

<template>
    <footer class="bg-dark border-t border-light/6 text-light/50">
        <div class="max-w-7xl mx-auto px-6 py-14 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-10">

            <!-- Brand -->
            <div class="lg:col-span-1">
                <Link :href="route('welcome')">
                    <img src="/img/primary-logo-dark.png" alt="Brignac Mortgage" class="h-9 w-auto mb-5">
                </Link>
                <p class="text-sm text-light/35 leading-relaxed">
                    Louisiana's trusted wholesale mortgage broker. Expert guidance for purchases, refinancing, and home equity loans.
                </p>
                <div class="flex items-center gap-2 mt-5">
                    <a href="https://www.facebook.com/brignacmortgage" target="_blank"
                       class="h-9 w-9 rounded-lg border border-light/8 hover:border-primary/50 hover:bg-primary/8 flex items-center justify-center text-light/30 hover:text-primary transition-all duration-200">
                        <svg class="w-4 h-4 fill-current" viewBox="0 0 24 24"><path d="M24 12.073c0-6.627-5.373-12-12-12s-12 5.373-12 12c0 5.99 4.388 10.954 10.125 11.854v-8.385H7.078v-3.47h3.047V9.43c0-3.007 1.792-4.669 4.533-4.669 1.312 0 2.686.235 2.686.235v2.953H15.83c-1.491 0-1.956.925-1.956 1.874v2.25h3.328l-.532 3.47h-2.796v8.385C19.612 23.027 24 18.062 24 12.073z"/></svg>
                    </a>
                    <a href="https://maps.app.goo.gl/6YyqmAGQ8nJtZ9Jk6" target="_blank"
                       class="h-9 w-9 rounded-lg border border-light/8 hover:border-primary/50 hover:bg-primary/8 flex items-center justify-center text-light/30 hover:text-primary transition-all duration-200">
                        <svg class="w-4 h-4 fill-current" viewBox="0 0 24 24"><path d="M12 2C8.13 2 5 5.13 5 9c0 5.25 7 13 7 13s7-7.75 7-13c0-3.87-3.13-7-7-7zm0 9.5c-1.38 0-2.5-1.12-2.5-2.5s1.12-2.5 2.5-2.5 2.5 1.12 2.5 2.5-1.12 2.5-2.5 2.5z"/></svg>
                    </a>
                </div>
            </div>

            <!-- Quick Links -->
            <div>
                <h3 class="text-light/80 font-semibold text-xs uppercase tracking-widest mb-5">Quick Links</h3>
                <ul class="space-y-3 text-sm">
                    <li><Link :href="route('welcome')"          class="footer-link">Home</Link></li>
                    <li><Link :href="route('about-us.index')"   class="footer-link">About Us</Link></li>
                    <li><Link :href="route('our-team.index')"   class="footer-link">Our Team</Link></li>
                    <li><Link :href="route('programs.index')"   class="footer-link">Loan Programs</Link></li>
                    <li><Link :href="route('contact-us.index')" class="footer-link">Contact Us</Link></li>
                </ul>
            </div>

            <!-- Legal -->
            <div>
                <h3 class="text-light/80 font-semibold text-xs uppercase tracking-widest mb-5">Legal</h3>
                <ul class="space-y-3 text-sm">
                    <li><Link :href="route('privacy-policy-website')" class="footer-link">Privacy Policy</Link></li>
                    <li><Link :href="route('disclaimers-website')"    class="footer-link">Disclaimers</Link></li>
                    <li><Link :href="route('terms-of-use-website')"   class="footer-link">Terms of Use</Link></li>
                </ul>
            </div>

            <!-- Contact -->
            <div>
                <h3 class="text-light/80 font-semibold text-xs uppercase tracking-widest mb-5">Contact</h3>
                <ul class="space-y-3 text-sm">
                    <li>
                        <a href="mailto:Shaun@brignacmortgage.com" class="footer-link flex items-start gap-2">
                            <span class="material-symbols-outlined text-primary mt-0.5 shrink-0" style="font-size:16px">mail</span>
                            Shaun@brignacmortgage.com
                        </a>
                    </li>
                    <li>
                        <a href="tel:+15045592821" class="footer-link flex items-center gap-2">
                            <span class="material-symbols-outlined text-primary shrink-0" style="font-size:16px">phone</span>
                            +1 504-559-2821
                        </a>
                    </li>
                    <li>
                        <a href="https://maps.app.goo.gl/R2Gu7ezyuNRhw3C6A" target="_blank" class="footer-link flex items-start gap-2">
                            <span class="material-symbols-outlined text-primary mt-0.5 shrink-0" style="font-size:16px">location_on</span>
                            21121 Waterfront East Dr,<br>Maurepas, LA
                        </a>
                    </li>
                </ul>
                <Link :href="route('contact-us.index')">
                    <button class="mt-6 bg-primary hover:bg-primary/90 text-dark text-sm font-bold px-6 py-2.5 rounded-full transition-colors duration-200 cursor-pointer">
                        Get Pre-Qualified
                    </button>
                </Link>
            </div>
        </div>

        <!-- Bottom bar -->
        <div class="border-t border-light/6 px-6 py-5">
            <div class="max-w-7xl mx-auto flex flex-col md:flex-row items-center justify-between gap-3 text-xs text-light/25">
                <p>© {{ currentYear }} Brignac Mortgage. All rights reserved.</p>
                <p class="text-center">
                    Brignac Mortgage and Consulting Services, LLC — NMLS #1928157 ·
                    <a href="https://maps.app.goo.gl/R2Gu7ezyuNRhw3C6A" target="_blank" class="hover:text-primary transition-colors">Maurepas, LA</a>
                </p>
            </div>
        </div>
    </footer>
</template>

<style scoped>
.footer-link {
    color: rgba(240, 238, 232, 0.40);
    text-decoration: none;
    transition: color 0.2s;
}
.footer-link:hover { color: #E37A52; }
</style>
